GET https://localhost:5000/client/locale/ru
###
GET https://localhost:5000/client/locale/ru
###
GET https://localhost:5000/client/locale/ru
###
GET https://localhost:5000/client/locale/ru
###
GET https://localhost:5000/client/locale/ru
###
GET https://localhost:5000/client/locale/ru
###
GET https://localhost:5000/client/locale/ru
###
GET https://localhost:5000/client/locale/ru
###
GET https://localhost:5000/client/locale/ru